# Generated by Django 3.0.7 on 2021-04-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210409_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='no_of_courses',
            new_name='no_of_owners',
        ),
    ]
